=== Omitg24/IIS-SEW/3. XML/Ejercicio-1/Tarea-4/SocialNetwork.xsd
<?xml version="1.0" encoding="Windows-1252"?>
<xs:schema xmlns="http://tempuri.org/SocialNetwork" elementFormDefault="qualified" targetNamespace="http://tempuri.org/SocialNetwork" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="persona">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="datos" />
				<xs:sequence minOccurs="0" maxOccurs="1">
					<xs:element ref="persona" />
					<xs:element ref="persona" />
					<xs:element ref="persona" />
				</xs:sequence>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="datos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="apellidos" />
				<xs:element ref="fnacimiento" />
				<xs:element ref="lnacimiento" />
				<xs:element ref="lresidencia" />
				<xs:element ref="fotografias" />
				<xs:element ref="videos" />
				<xs:element ref="comentario" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="apellidos" type="xs:string" />
	<xs:element name="fnacimiento" type="xs:string" />
	<xs:element name="lnacimiento">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lnombre" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="lresidencia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lnombre" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="unbounded">
				<xs:element ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="comentario" type="xs:string" />
	<xs:element name="fotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enlace" />
			</xs:sequence>
			<xs:attribute default="" name="descripcion" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enlace" />
			</xs:sequence>
			<xs:attribute default="" name="descripcion" type="xs:string" />
		</xs:complexType>
	</xs:element>
	<xs:element name="enlace" type="xs:string" />
	<xs:element name="descripcion" type="xs:string" />
	<xs:element name="lnombre" type="xs:string" />
	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud" type="xs:string" />
	<xs:element name="latitud" type="xs:string" />
	<xs:element name="altitud" type="xs:string" />
</xs:schema>

=== Omitg24/IIS-SEW/3. XML/Ejercicio-2/Tarea-2/SocialNetwork.xml
<?xml version="1.0" encoding="UTF-8"?>
<persona 
xmlns="https://uniovi.es"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://uniovi.es SocialNetwork.xsd"
>
	<datos>
		<nombre>Omar</nombre>
		<apellidos>Teixeira González</apellidos>
		<fnacimiento>2002-03-24</fnacimiento>
		<lnacimiento>
			<lnombre>Oviedo</lnombre>
			<coordenadas>
				<longitud>43.356923</longitud>
				<latitud>-5.867880</latitud>
				<altitud>242</altitud>
			</coordenadas>
		</lnacimiento>
		<lresidencia>
			<lnombre>Madrid</lnombre>
			<coordenadas>
				<longitud>40.4253205</longitud>
				<latitud>-3.7127347</latitud>
				<altitud>205</altitud>
			</coordenadas>
		</lresidencia>
		<fotografias>
			<fotografia descripcion="Foto de perfil de Omar sobre Husky adulto">
				<enlace>husky_adulto.png</enlace>
			</fotografia>
			<fotografia descripcion="Foto de portada de Omar sobre Golden retriever cachorro">
				<enlace>golden_cachorro.png</enlace>				
			</fotografia>
			<fotografia descripcion="Foto de muestra de Omar sobre Husky cachorro">
				<enlace>husky_cachorro.png</enlace>				
			</fotografia>
			<fotografia descripcion="Foto de anexo de Omar sobre Golden retriever adulto">
				<enlace>golden_adulto.png</enlace>				
			</fotografia>
		</fotografias>
		<videos>
			<video descripcion="Video de Omar sobre  husky cachorro aullando">
				<enlace>https://www.youtube.com/shorts/WTpyXOKXoN0</enlace>				
			</video>
			<video descripcion="Video de Omar sobre  Golden retrievers">
				<enlace>https://www.youtube.com/shorts/FVz9IiBqlgY</enlace>				
			</video>
		</videos>
		<comentario>Estudiante de Ingeniería Informática</comentario>
	</datos>
	<persona>
		<datos>
			<nombre>Alba</nombre>
			<apellidos>Francos Ablanedo</apellidos>
			<fnacimiento>2002-06-14</fnacimiento>
			<lnacimiento>
				<lnombre>Oviedo</lnombre>
				<coordenadas>
					<longitud>43.356923</longitud>
					<latitud>-5.867880</latitud>
					<altitud>242</altitud>
				</coordenadas>
			</lnacimiento>
			<lresidencia>
				<lnombre>Madrid</lnombre>
				<coordenadas>
					<longitud>40.4253205</longitud>
					<latitud>-3.7127347</latitud>
					<altitud>205</altitud>
				</coordenadas>
			</lresidencia>
			<fotografias>
				<fotografia descripcion="Foto de perfil de Alba sobre Samoyedo">				
					<enlace>samoyedo.png</enlace>					
				</fotografia>
			</fotografias>
			<videos>
				<video descripcion="Video de Alba sobre Samoyedo">
					<enlace>https://www.youtube.com/shorts/zbFU91cFTjk</enlace>
					
				</video>
				<video descripcion="Video de Alba sobre Samoyedo feliz">
					<enlace>https://www.youtube.com/shorts/zT6bNYBxyFs</enlace>					
				</video>
			</videos>
			<comentario>Estudiante de Logopedia</comentario>
		</datos>
		<persona>
			<datos>
				<nombre>Raúl</nombre>
				<apellidos>Fernández España</apellidos>
				<fnacimiento>2001-04-10</fnacimiento>
				<lnacimiento>
					<lnombre>Pola de Laviana</lnombre>
					<coordenadas>
						<longitud>43.252652</longitud>
						<latitud>-5.574053</latitud>
						<altitud>285</altitud>
					</coordenadas>
				</lnacimiento>
				<lresidencia>
					<lnombre>Valencia</lnombre>
					<coordenadas>
						<longitud>39.4077643</longitud>
						<latitud>-0.4315506</latitud>
						<altitud>285</altitud>
					</coordenadas>
				</lresidencia>
				<fotografias>
					<fotografia descripcion="Foto de perfil de Raúl sobre eucalipto">
						<enlace>eucalipto.png</enlace>						
					</fotografia>
				</fotografias>
				<videos>
					<video descripcion="Video de Raúl sobre como cuidar eucaliptos">
						<enlace>https://www.youtube.com/watch?v=nbfLumrZhm4</enlace>						
					</video>
					<video descripcion="Video de Raúl sobre como cuidar eucaliptos en interior">
						<enlace>https://www.youtube.com/watch?v=b5E1hko05t4</enlace>						
					</video>
					<video descripcion="Video de Raúl sobre información sobre los eucaliptos">
						<enlace>https://www.youtube.com/watch?v=S6xNDVYBU1k</enlace>
					</video>
				</videos>
				<comentario>Estudiante de Ingeniería Informática</comentario>
			</datos>
		</persona>
		<persona>
			<datos>
				<nombre>Carla</nombre>
				<apellidos>Muñiz Testón</apellidos>
				<fnacimiento>2001-04-03</fnacimiento>
				<lnacimiento>
					<lnombre>Oviedo</lnombre>
					<coordenadas>
						<longitud>43.356923</longitud>
						<latitud>-5.867880</latitud>
						<altitud>242</altitud>
					</coordenadas>
				</lnacimiento>
				<lresidencia>
					<lnombre>Valencia</lnombre>
					<coordenadas>
						<longitud>39.4077643</longitud>
						<latitud>-0.4315506</latitud>
						<altitud>285</altitud>
					</coordenadas>
				</lresidencia>
				<fotografias>
					<fotografia descripcion="Foto de perfil de Carla sobre Corgi corriendo">
						<enlace>corgi_corriendo.png</enlace>						
					</fotografia>
					<fotografia descripcion="Foto de portada de Carla sobre Corgi corriendo">
						<enlace>corgi_sonriendo.png</enlace>						
					</fotografia>
				</fotografias>
				<videos>					
				</videos>
				<comentario>Estudiante de Derecho</comentario>
			</datos>
		</persona>
		<persona>
			<datos>
				<nombre>Luis Manuel</nombre>
				<apellidos>Solares García</apellidos>
				<fnacimiento>2002-09-03</fnacimiento>
				<lnacimiento>
					<lnombre>Pola de Laviana</lnombre>
					<coordenadas>
						<longitud>43.252652</longitud>
						<latitud>-5.574053</latitud>
						<altitud>285</altitud>
					</coordenadas>
				</lnacimiento>
				<lresidencia>
					<lnombre>Salamanca</lnombre>
					<coordenadas>
						<longitud>40.9634372</longitud>
						<latitud>-5.6867216</latitud>
						<altitud>20</altitud>
					</coordenadas>
				</lresidencia>
				<fotografias>
					<fotografia descripcion="Foto de perfil de Luisma sobre Goku">
						<enlace>goku.png</enlace>						
					</fotografia>
				</fotografias>
				<videos>
				</videos>
				<comentario>Estudiante de Ingeniería Informática</comentario>
			</datos>
		</persona>
	</persona>
	<persona>
		<datos>
			<nombre>Israel</nombre>
			<apellidos>Solís Iglesias</apellidos>
			<fnacimiento>2002-08-03</fnacimiento>
			<lnacimiento>
				<lnombre>Villa</lnombre>
				<coordenadas>
					<longitud>43.328117</longitud>
					<latitud>-5.721802</latitud>
					<altitud>199</altitud>
				</coordenadas>
			</lnacimiento>
			<lresidencia>
				<lnombre>Andorra</lnombre>
				<coordenadas>
					<longitud>42.5421978</longitud>
					<latitud>1.457612</latitud>
					<altitud>281</altitud>
				</coordenadas>
			</lresidencia>
			<fotografias>
				<fotografia descripcion="Foto de perfil de Israel sobre tortugas">
					<enlace>tortugas.png</enlace>					
				</fotografia>
			</fotografias>
			<videos>
			</videos>
			<comentario>Estudiante de Ingeniería Informática</comentario>
		</datos>
		<persona>
			<datos>
				<nombre>Adrián</nombre>
				<apellidos>Alves Morales</apellidos>
				<fnacimiento>2002-06-08</fnacimiento>
				<lnacimiento>
					<lnombre>Avilés</lnombre>
					<coordenadas>
						<longitud>43.5554436</longitud>
						<latitud>-5.9222466</latitud>
						<altitud>20</altitud>
					</coordenadas>
				</lnacimiento>
				<lresidencia>
					<lnombre>Málaga</lnombre>
					<coordenadas>
						<longitud>36.7182015</longitud>
						<latitud>-4.5193062</latitud>
						<altitud>20</altitud>
					</coordenadas>
				</lresidencia>
				<fotografias>
					<fotografia descripcion="Foto de perfil de Alves sobre Final Fantasy XIV">
						<enlace>final_fantasy_1.png</enlace>
					</fotografia>
					<fotografia descripcion="Foto de portada de Alves sobre el personaje de Final Fantasy XIV">
						<enlace>final_fantasy_2.png</enlace>						
					</fotografia>
				</fotografias>
				<videos>
					<video descripcion="Video de Alves sobre gameplay no comentado de Final Fantasy XIV">
						<enlace>https://www.youtube.com/watch?v=rr6LoM9h4xw</enlace>
					</video>
					<video descripcion="Video de Alves sobre gameplay no comentado del DLC de Final Fantasy XIV">
						<enlace>https://www.youtube.com/watch?v=FB7L6_05UqY</enlace>
					</video>
				</videos>
				<comentario>Estudiante de Ingeniería Informática</comentario>
			</datos>
		</persona>
		<persona>
			<datos>
				<nombre>David</nombre>
				<apellidos>Warzynski Abril</apellidos>
				<fnacimiento>2001-08-08</fnacimiento>
				<lnacimiento>
					<lnombre>Villa</lnombre>
					<coordenadas>
						<longitud>43.328117</longitud>
						<latitud>-5.721802</latitud>
						<altitud>199</altitud>
					</coordenadas>
				</lnacimiento>
				<lresidencia>
					<lnombre>Villaescusa</lnombre>
					<coordenadas>
						<longitud>43.3623236</longitud>
						<latitud>-3.8907856</latitud>
						<altitud>218</altitud>
					</coordenadas>
				</lresidencia>
				<fotografias>
					<fotografia descripcion="Foto de perfil de David sobre Sova con arco">
						<enlace>sova.png</enlace>
					</fotografia>
					<fotografia descripcion="Foto de portada de David sobre Sova de Valorant">
						<enlace>sova_valorant.png</enlace>
					</fotografia>
					<fotografia descripcion="Foto de muestra de David sobre Sova con arma de fuego">
						<enlace>sova_arma.png</enlace>
					</fotografia>
				</fotografias>
				<videos>
					<video descripcion="Video de David sobre gameplay no comentado de Sova">
						<enlace>https://www.youtube.com/watch?v=K6FrFhlAKOs</enlace>						
					</video>
					<video descripcion="Video de David sobre gameplay no comentado de Sova 2">
						<enlace>https://www.youtube.com/watch?v=Yp7OcIeo6CU</enlace>						
					</video>
				</videos>
				<comentario>Estudiante de Ingeniería Informática</comentario>
			</datos>
		</persona>
		<persona>
			<datos>
				<nombre>Victor</nombre>
				<apellidos>Sánchez Martín</apellidos>
				<fnacimiento>2002-04-10</fnacimiento>
				<lnacimiento>
					<lnombre>Vallecas</lnombre>
					<coordenadas>
						<longitud>40.3514257</longitud>
						<latitud>-3.6526058</latitud>
						<altitud>199</altitud>
					</coordenadas>
				</lnacimiento>
				<lresidencia>
					<lnombre>Madrid</lnombre>
					<coordenadas>
						<longitud>40.4379332</longitud>
